# Generated by Django 5.1.3 on 2025-01-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtitle')),
                ('subtitle_uz', models.CharField(max_length=255, null=True, verbose_name='subtitle')),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(max_length=255, null=True, verbose_name='subtitle')),
                ('color_right', models.CharField(default='#000000', max_length=255, verbose_name='color right')),
                ('color_left', models.CharField(default='#000000', max_length=255, verbose_name='color left')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'BannerModel',
                'verbose_name_plural': 'BannerModels',
                'db_table': 'banner',
            },
        ),
    ]
