# Generated by Django 5.1.5 on 2025-01-24 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_alter_notificationmodel_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='notifications', through='shared.UserNotificationModel', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
