# Generated by Django 5.1.5 on 2025-01-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_merge_20250129_1512'),
        ('shared', '0011_merge_20250129_1548'),
    ]

    operations = [
    ]
