# Generated by Django 5.2 on 2025-04-25 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0012_merge_20250129_1658"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications",
                through="shared.UserNotificationModel",
                through_fields=("notification", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
