# Generated by Django 5.1.3 on 2024-12-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('user', 'User'), ('psixolog', 'Psixolog'), ('lawyer', 'Lawyer')], default='user', max_length=255),
        ),
    ]
