# Generated by Django 5.1.3 on 2025-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_moderatormodel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatormodel',
            name='experience',
            field=models.CharField(default=0),
        ),
    ]
