networks:
  dokploy-network:
    external: true

volumes:
  pg_data: null
  rabbitmq: null
  pycache: null

services:
  web:
    networks:
      - dokploy-network
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: ${COMMAND:-sh ./entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - './:/code'
      - ../files/media:/code/resources/media
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    networks:
      - dokploy-network
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - dokploy-network
    restart: always
    image: redis
