networks:
  helping_hand:
    driver: bridge
  dokploy-network:
    external: true

volumes:
  pg_data: null
  rabbitmq: null
  pycache: null

services:
  nginx:
    networks:
      - helping_hand
      - dokploy-network
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.test.rule=Host(`dokploy.jscorp.uz`)
      - traefik.http.routers.test.entrypoints=web
      - traefik.http.services.test.loadbalancer.server.port=80
  web:
    networks:
      - helping_hand
      - dokploy-network
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: ${COMMAND:-sh ./entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - .:/code
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    networks:
      - helping_hand
      - dokploy-network
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - helping_hand
      - dokploy-network
    restart: always
    image: redis
  rabbitmq:
    networks:
      - helping_hand
      - dokploy-network
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_PASS=2309
      - RABBITMQ_DEFAULT_VHOST=vhost
    volumes:
      - rabbitmq:/var/lib/rabbitmq
