networks:
  helping_hand:
    driver: bridge

volumes:
  pg_data: null
  rabbitmq: null

services:
  nginx:
    networks:
      - helping_hand
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
  web:
    networks:
      - helping_hand
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: ${COMMAND:-sh ./entrypoint.sh}
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  db:
    networks:
      - helping_hand
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - helping_hand
    restart: always
    image: redis
  rabbitmq:
    networks:
      - helping_hand
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_PASS=2309
      - RABBITMQ_DEFAULT_VHOST=vhost
    volumes:
      - rabbitmq:/var/lib/rabbitmq
