FROM python:3.12-bookworm

WORKDIR /code

# Install required dependencies including a specific version of GDAL
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    binutils \
    gdal-bin \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    g++ \
    make \
    wkhtmltopdf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify GDAL version (for troubleshooting)
RUN gdalinfo --version

# Install Python dependencies
COPY ./ /code
RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip install -r requirements.txt

CMD ["sh", "./resources/scripts/entrypoint.sh"]
