FROM jscorptech/django:v1.0.0


ARG SCRIPT="entrypoint.sh"
ENV SCRIPT=$SCRIPT

WORKDIR /code

# Install required dependencies that are missing in the base image (Alpine based)
# Note: wkhtmltopdf is problematic on Alpine, might need a different approach if needed
RUN apk update && \
    apk add --no-cache \
    binutils \
    gdal \
    gdal-dev \
    geos-dev \
    proj-dev \
    g++ \
    make \
    ttf-dejavu \
    ttf-freefont \
    ttf-liberation \
    pango-dev \
    libffi-dev \
    py3-pip \
    python3-dev \
    jpeg-dev \
    zlib-dev \
    freetype-dev \
    lcms2-dev \
    openjpeg-dev \
    tiff-dev \
    tk-dev \
    tcl-dev \
    harfbuzz-dev \
    fribidi-dev \
    ghostscript-dev

COPY requirements.txt /code/requirements.txt

# Install to the existing venv
RUN uv pip install -r requirements.txt

COPY ./ /code

RUN chmod +x /code/resources/scripts/$SCRIPT

CMD sh /code/resources/scripts/$SCRIPT
