FROM postgres:16

# Install PostGIS and dependencies
RUN apt-get update && \
    apt-get install -y postgis postgresql-16-postgis-3 postgresql-16-postgis-3-scripts && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV POSTGIS_VERSION 3
