FROM jscorptech/django:v1.0.0

ARG SCRIPT="entrypoint.sh"
ENV SCRIPT=$SCRIPT

WORKDIR /code

# Install required dependencies that are missing in the base image (Alpine based)
# Note: wkhtmltopdf is problematic on Alpine, might need a different approach if needed
RUN apk update && \
    apk add --no-cache \
    binutils \
    gdal \
    gdal-dev \
    geos-dev \
    proj-dev \
    g++ \
    make \
    ttf-dejavu \
    ttf-freefont \
    ttf-liberation

COPY requirements.txt /code/requirements.txt

# Use uv for faster installation
RUN uv pip install --system -r requirements.txt

COPY ./ /code

RUN chmod +x /code/resources/scripts/$SCRIPT

CMD sh /code/resources/scripts/$SCRIPT
