# Generated by Django 5.1.3 on 2025-01-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_postmodel_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='views'),
        ),
    ]
