# Generated by Django 5.1.3 on 2025-01-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_postmodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='news_type',
            field=models.CharField(choices=[('psixolog', 'Psixolog'), ('lawyer', 'Lawyer'), ('business', 'Business')], default='business', max_length=255, verbose_name='type'),
        ),
    ]
