# Generated by Django 5.1.3 on 2024-12-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic", models.CharField(max_length=255, verbose_name="topic")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="description")),
                ("time", models.PositiveIntegerField(default=0, verbose_name="time")),
            ],
            options={
                "verbose_name": "TestModel",
                "verbose_name_plural": "TestModels",
                "db_table": "test",
            },
        ),
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(verbose_name="question")),
                ("file", models.FileField(blank=True, null=True, upload_to="questions/", verbose_name="file")),
                ("is_any", models.BooleanField(default=False, verbose_name="is any")),
                ("is_many", models.BooleanField(default=False, verbose_name="is many")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="education.testmodel",
                        verbose_name="test",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuestionModel",
                "verbose_name_plural": "QuestionModels",
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="VariantModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variant", models.CharField(max_length=255, verbose_name="variant")),
                ("is_true", models.BooleanField(default=False, verbose_name="is true")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="education.questionmodel",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "VariantModel",
                "verbose_name_plural": "VariantModels",
                "db_table": "variant",
            },
        ),
        migrations.CreateModel(
            name="AnswerModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="education.questionmodel",
                        verbose_name="question",
                    ),
                ),
                (
                    "variant",
                    models.ManyToManyField(related_name="answers", to="education.variantmodel", verbose_name="variant"),
                ),
            ],
            options={
                "verbose_name": "AnswerModel",
                "verbose_name_plural": "AnswerModels",
                "db_table": "answer",
            },
        ),
    ]
