# Generated by Django 5.1.3 on 2024-12-24 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0005_alter_tutorialmodel_test"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "GuideModel",
                "verbose_name_plural": "GuideModels",
                "db_table": "guide",
            },
        ),
        migrations.RemoveField(
            model_name="tutorialmodel",
            name="type",
        ),
        migrations.AddField(
            model_name="tutorialmodel",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="position"),
        ),
        migrations.AddField(
            model_name="tutorialmodel",
            name="source",
            field=models.URLField(blank=True, null=True, verbose_name="source"),
        ),
        migrations.AddField(
            model_name="tutorialmodel",
            name="tags",
            field=models.JSONField(blank=True, null=True, verbose_name="tags"),
        ),
        migrations.AddField(
            model_name="tutorialmodel",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="tutorials", to=settings.AUTH_USER_MODEL, verbose_name="users"
            ),
        ),
    ]
