# Generated by Django 5.1.3 on 2024-12-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_guidemodel_remove_tutorialmodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmodel',
            name='tags',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='tags'),
        ),
    ]
