# Generated by Django 5.1.3 on 2024-12-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_guidemodel_guide_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='guide_type',
            field=models.CharField(choices=[('psixolog', 'Psixolog'), ('lawyer', 'Lawyer'), ('business', 'Business')], max_length=255, verbose_name='type'),
        ),
    ]
