# Generated by Django 5.1.3 on 2024-12-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_guidemodel_guide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='tutorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education.tutorialmodel', verbose_name='tutorial'),
            preserve_default=False,
        ),
    ]
