# Generated by Django 5.1.3 on 2024-12-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_taskresultmodel_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresultmodel',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='taskresultmodel',
            name='is_file_answer',
            field=models.BooleanField(default=False, verbose_name='is answer file'),
        ),
    ]
