# Generated by Django 5.1.3 on 2024-12-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_examresultmodel_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='image',
        ),
    ]
