# Generated by Django 5.1.3 on 2025-01-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_remove_taskmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialmodel',
            name='tags',
        ),
    ]
