# Generated by Django 5.1.3 on 2025-01-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0025_tutorialmodel_desc_kaa_tutorialmodel_desc_kril_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionmodel",
            name="file",
        ),
        migrations.DeleteModel(
            name="AnswerModel",
        ),
    ]
