# Generated by Django 5.1.6 on 2025-02-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0030_alter_variantmodel_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examresultmodel",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="sertificatemodel",
            name="exam",
        ),
    ]
