# Generated by Django 5.2 on 2025-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0035_guidemodel_file_kaa_guidemodel_file_kril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificatemodel',
            name='tutorial_type',
            field=models.CharField(blank=True, choices=[('psixolog', 'Psixolog'), ('lawyer', 'Lawyer'), ('business', 'Business'), ('document', 'Document')], null=True, verbose_name='tutorial type'),
        ),
    ]
