# Generated by Django 5.1.3 on 2024-12-13 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupmodel', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
