# Generated by Django 5.1.3 on 2024-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_messagemodel_file_alter_messagemodel_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="groups/", verbose_name="image"),
        ),
        migrations.AddField(
            model_name="groupmodel",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="is:public"),
        ),
    ]
