# Generated by Django 5.1.3 on 2024-12-16 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_groupmodel_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmodel",
            name="users",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="chats", to=settings.AUTH_USER_MODEL, verbose_name="users"
            ),
        ),
    ]
