# Generated by Django 5.1.3 on 2024-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_groupmodel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='chat_type',
            field=models.CharField(blank=True, choices=[('lawyer', 'Lawyer'), ('psixolog', 'Psixolog')], null=True, verbose_name='chat type'),
        ),
    ]
