# Generated by Django 5.1.3 on 2025-01-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_groupmodel_chat_type_alter_groupmodel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodel",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="is read"),
        ),
    ]
